In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])

In [4]:
a.ndim

1

In [5]:
b.shape

(2, 3)

In [6]:
b.dtype
a.dtype

dtype('int32')

In [7]:
b.dtype='int16'
b.dtype

dtype('int16')

In [8]:
a.itemsize

4

In [9]:
a.size
b.size
a.nbytes

12

In [10]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [11]:
a[1,5]

13

In [12]:
a[1,-2]

13

In [13]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#get a specific column
a[:,2]

array([ 3, 10])

In [15]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [16]:
a[:,2]=5
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 13, 14]])

In [17]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
#get a specific element(work outside in)
b[0,1,0]

3

In [19]:
#replce
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [20]:
#all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#all ones matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
#any other numbers
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [23]:
# anyother number(full_like)
np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
#Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(a.shape)

array([[0.25178194, 0.56997097, 0.64433223, 0.14690893, 0.82382381,
        0.84499798, 0.6712931 ],
       [0.96298665, 0.6798874 , 0.40071803, 0.17182268, 0.7294996 ,
        0.13165571, 0.06165   ]])

In [25]:
#random integer values
np.random.randint(1,7,size=(3,3))

array([[6, 5, 6],
       [6, 3, 1],
       [3, 3, 3]])

In [26]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
# r2=np.ones((5,5))
# r2[1:4,1:4]=0
# r2[2,2]=9
# r2
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
####BECAREFUL WHEN COPYING ARRAYS
a=np.array([1,2,3])
b=a
b[0]=100 #changing b will also change a
b,a

#solution
a=np.array([1,2,3])
b=a.copy()
b[0]=100
a,b

(array([1, 2, 3]), array([100,   2,   3]))

In [30]:
#mathmatics
a=np.array([1,2,3,4])

In [31]:
#take the sin of all the valuues
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
#Linear algebra
a=np.full((2,3),1)
b=np.full((3,2),2)
a,b
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [33]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [34]:
##Statistics
stats=np.array([[1,2,4],[3,5,6]])
np.min(stats,axis=1)

array([1, 3])

In [35]:
np.max(stats,axis=0)

array([3, 5, 6])

In [36]:
np.sum(stats,axis=1)

array([ 7, 14])

In [37]:
before = stats=np.array([[1,2,3,4],[5,6,7,8]])
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
np.stack([v1,v2],axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

In [41]:
#BOOleam masking and advance indexing
a=np.random.randint(1,7,(2,3))
a

array([[2, 2, 2],
       [2, 1, 3]])

In [42]:
a[a>3]#you can index with a list in numpy

array([], dtype=int32)

In [43]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[[1,2,8]]

array([2, 3, 9])

In [44]:
np.any(a>3,axis=0)

array([False, False, False])

In [45]:
np.any(a>3,axis=1)

array([False, False])

In [46]:
np.all(a>3,axis=0)

array([False, False, False])

In [47]:
(a>3) &(a<6)

array([[False, False, False],
       [False, False, False]])

In [48]:
~((a>3)&(a<5))

array([[ True,  True,  True],
       [ True,  True,  True]])

In [49]:
test=np.random.randint(1,31,(5,5))
print(test)
print(test[2:4,0:2])
print(test[[0,1,2,3],[1,2,3,4]])

[[15  7  7  7 25]
 [23 28 13 21 24]
 [25 12 17 28  9]
 [14 22 19 23 26]
 [30  6 24 11  6]]
[[25 12]
 [14 22]]
[ 7 13 28 26]
